### ISSUE TITLE
Pasting an address into recipient field gives "Recipient is not on the XMTP network" error

### ISSUE THREAD

**Issue by cpvdeveloper** [liteflow-labs/chat#8]
When I paste an address directly into the "recipient" field, I seem to always be getting the `Recipient is not on the XMTP network error`, even when I already have a working chat with that recipient. The screenshot shows an existing chat with a user, but an error when pasting that user's address into the recipient field.

<img width="450" alt="Screenshot 2565-10-18 at 09 16 17" src="https://user-images.githubusercontent.com/88588186/196433609-3a033cae-d53b-44e9-afb0-857a926df764.png">

**Comment by antho1404** [comment]
fixed by https://github.com/liteflow-labs/chat/pulls
